services:
  livekit-server:
    image: livekit/livekit-server:latest
    container_name: livekit-server
    ports:
      - "7880:7880"
      - "7881:7881"
    env_file:
      - server/env
    # command: ["livekit-server", "--dev", "--bind", "0.0.0.0"]
    volumes:
      - ./server/livekit-config.yaml:/livekit.yaml
  
  agent:
    build: ./agent
    depends_on:
      - livekit-server
    environment:
      - LIVEKIT_URL=ws://livekit-server:7880
      - LIVEKIT_API_KEY=Jaif5tajebueVoh0peiji2PeRieroh0d
      - LIVEKIT_API_SECRET=ood2Oodoti9lie5XaiW7jieJshooSoo4
  
  web:
    build: ./web
    depends_on:
    - livekit-server
    environment:
      - LIVEKIT_URL=ws://livekit-server:7880
      - LIVEKIT_API_KEY=Jaif5tajebueVoh0peiji2PeRieroh0d
      - LIVEKIT_API_SECRET=ood2Oodoti9lie5XaiW7jieJshooSoo4
    
